import { CheckCircle2, ChevronLeft, Clock3, Upload } from 'lucide-react';
import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import { formatStartingPrice } from '../utils/price';

type Service = { id: number; code: string; name: string; category: string; description: string; priceLabel: string; depositAmount: number };
type Dentist = { id: number; code: string; name: string; specialty: string };
type Slot = { id: number; startsAt: string; endsAt: string };
const apiBase = import.meta.env.VITE_API_BASE_URL ?? '/api';
const mockServices: Service[] = [
  { id: 3, code: 'FILLING', name: 'อุดฟัน', category: 'งานทั่วไป', description: 'บูรณะฟันผุหรือฟันสึก', priceLabel: '550–1,000 บาท', depositAmount: 400 },
  { id: 4, code: 'SCALING', name: 'ขูดหินปูนทั้งปาก', category: 'งานทั่วไป', description: 'ดูแลเหงือกและกำจัดคราบหินปูน', priceLabel: '700 บาท', depositAmount: 400 },
  { id: 6, code: 'FLUORIDE', name: 'เคลือบฟลูออไรด์', category: 'ทันตกรรมสำหรับเด็ก', description: 'เสริมความแข็งแรงให้ผิวฟัน', priceLabel: '300 บาท', depositAmount: 400 },
  { id: 10, code: 'ROOT_CANAL', name: 'รักษาคลองรากฟันหน้า', category: 'งานรักษาคลองรากฟันแท้', description: 'รักษาคลองรากฟันตามแผนการรักษา', priceLabel: '4,250–5,250 บาท', depositAmount: 400 },
  { id: 19, code: 'X_RAY', name: 'เอกซเรย์ในช่องปาก', category: 'รากฟันเทียมและเอกซเรย์', description: 'ตรวจภาพรังสีเฉพาะตำแหน่ง', priceLabel: '150–200 บาท', depositAmount: 400 },
];
const mockDentists: Dentist[] = [
  { id: 1, code: 'DEN', name: 'ทพญ. พิมพ์ใจ สุขสันต์', specialty: 'ทันตกรรมทั่วไป' },
  { id: 2, code: 'DNT', name: 'ทพ. ณัฐวุฒิ ยิ้มแย้ม', specialty: 'บูรณะฟัน' },
];
const commonProceduresByCategory: Record<string, string[]> = {
  'งานทั่วไป': ['อุดฟัน', 'ขูดหินปูนทั้งปาก', 'ถอนฟัน/ถอนฟันยาก'],
  'ทันตกรรมสำหรับเด็ก': ['เคลือบฟลูออไรด์', 'เคลือบหลุมร่องฟัน', 'ครอบฟันเหล็กไร้สนิม'],
  'งานรักษาคลองรากฟันแท้': ['รักษาคลองรากฟันหน้า', 'รักษาคลองรากฟันกรามน้อย', 'รักษาคลองรากฟันกราม'],
  'งานบูรณะและฟันเทียม': ['ครอบฟัน', 'เดือยฟันและแกนฟัน', 'ฟันเทียมอะคริลิกบางส่วน'],
  'รากฟันเทียมและเอกซเรย์': ['เอกซเรย์ในช่องปาก', 'Panoramic / Cephalometry', 'รากฟันเทียมมาตรฐาน'],
};
const dateString = (offset = 1) => { const value = new Date(); value.setDate(value.getDate() + offset); return value.toISOString().slice(0, 10); };
const timeFormatter = new Intl.DateTimeFormat('th-TH', { hour: '2-digit', minute: '2-digit' });
const timeLabel = (value: string) => timeFormatter.format(new Date(value));
export function BookingPage() {
  const [step, setStep] = useState(1); const [services, setServices] = useState<Service[]>(mockServices); const [dentists, setDentists] = useState<Dentist[]>([]); const [slots, setSlots] = useState<Slot[]>([]);
  const [bookingFlow, setBookingFlow] = useState<'PROCEDURE_AND_DENTIST' | 'DENTIST_ONLY' | 'TIME_ONLY'>('PROCEDURE_AND_DENTIST');
  const [category, setCategory] = useState<string | null>(null); const [service, setService] = useState<Service | null>(null); const [dentist, setDentist] = useState<Dentist | null>(null); const [selectedDate, setSelectedDate] = useState(() => dateString()); const [slot, setSlot] = useState<Slot | null>(null);
  const [phone, setPhone] = useState(''); const [reference, setReference] = useState(''); const [queueNumber, setQueueNumber] = useState(''); const [amount, setAmount] = useState(0); const [reservationPaymentRequired, setReservationPaymentRequired] = useState(true); const [acknowledged, setAcknowledged] = useState(false); const [qrCode, setQrCode] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const categories = useMemo(() => [...new Set(services.map((item) => item.category))], [services]);
  const procedures = useMemo(() => services.filter((item) => item.category === category), [category, services]);
  const bookingStepLabels = bookingFlow === 'DENTIST_ONLY'
    ? ['ทันตแพทย์', 'วันและเวลา', 'เบอร์โทร', 'ยืนยันการจอง']
    : bookingFlow === 'TIME_ONLY'
      ? ['วันและเวลา', 'เบอร์โทร', 'ยืนยันการจอง']
      : ['หมวดบริการ', 'หัตถการ', 'ทันตแพทย์', 'วันและเวลา', 'เบอร์โทร', 'ชำระเงิน'];
  const displayedStep = bookingFlow === 'DENTIST_ONLY' ? step - 2 : bookingFlow === 'TIME_ONLY' ? step - 3 : step;
  const selectCategory = (next: string) => { setCategory(next); setService(null); setDentist(null); setSlot(null); setDentists([]); setSlots([]); setMessage(''); setStep(2); };
  const selectService = async (next: Service) => { setService(next); setDentist(null); setSlot(null); setSlots([]); setLoading(true); setMessage(''); try { const response = await fetch(`${apiBase}/services/${next.id}/dentists`); const data = response.ok ? await response.json() : null; setDentists(data?.dentists ?? mockDentists); } catch { setDentists(mockDentists); } finally { setLoading(false); setStep(3); } };
  const loadAvailability = useCallback(async (nextDentist = dentist, nextDate = selectedDate, nextBookingFlow = bookingFlow) => { if ((nextBookingFlow === 'PROCEDURE_AND_DENTIST' && (!nextDentist || !service)) || (nextBookingFlow === 'DENTIST_ONLY' && !nextDentist)) return; setLoading(true); try { const query = new URLSearchParams({ ...(nextBookingFlow === 'PROCEDURE_AND_DENTIST' ? { serviceId: String(service!.id) } : {}), date: nextDate }); const response = await fetch(nextBookingFlow === 'TIME_ONLY' ? `${apiBase}/availability?${query}` : `${apiBase}/dentists/${nextDentist!.id}/availability?${query}`); const data = response.ok ? await response.json() : null; setSlots(data?.slots ?? []); } catch { setMessage('ไม่สามารถเชื่อมต่อระบบตารางนัดหมายได้ในขณะนี้'); } finally { setLoading(false); } }, [bookingFlow, dentist, selectedDate, service]);
  useEffect(() => { fetch(`${apiBase}/services`).then((response) => response.ok ? response.json() : null).then((data) => data?.services && setServices(data.services)).catch(() => undefined); fetch(`${apiBase}/booking-config`).then((response) => response.ok ? response.json() : null).then(async (data) => { if (data?.bookingFlow === 'TIME_ONLY') { setBookingFlow('TIME_ONLY'); setStep(4); } if (data?.bookingFlow === 'DENTIST_ONLY') { setBookingFlow('DENTIST_ONLY'); const response = await fetch(`${apiBase}/dentists`); const dentistsData = response.ok ? await response.json() : null; setDentists((dentistsData?.dentists ?? []).map((item: { id: number; name: string; specialty?: string }) => ({ id: item.id, code: `DENTIST-${item.id}`, name: item.name, specialty: item.specialty ?? 'ทันตกรรมทั่วไป' }))); setStep(3); } }).catch(() => undefined); }, []);
  useEffect(() => {
    if (bookingFlow !== 'TIME_ONLY' || step !== 4) return;
    const timeout = window.setTimeout(() => { void loadAvailability(); }, 0);
    return () => window.clearTimeout(timeout);
  }, [bookingFlow, loadAvailability, step]);
  const selectDentist = async (next: Dentist) => { setDentist(next); setSlot(null); await loadAvailability(next); setStep(4); };
  const createBooking = async (event: FormEvent) => { event.preventDefault(); if (!slot || (bookingFlow !== 'TIME_ONLY' && !dentist) || (bookingFlow === 'PROCEDURE_AND_DENTIST' && !service)) return; setLoading(true); setMessage(''); try { const response = await fetch(`${apiBase}/appointments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...(service ? { serviceId: service.id } : {}), ...(dentist ? { dentistId: dentist.id } : {}), slotId: slot.id, phone }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); const paymentRequired = data.appointment.reservationPaymentRequired !== false; setReference(data.appointment.reference); setQueueNumber(data.appointment.queueNumber); setAmount(data.appointment.paymentAmount); setReservationPaymentRequired(paymentRequired); setAcknowledged(false); setStep(6); if (paymentRequired) { const qrResponse = await fetch(`${apiBase}/appointments/${data.appointment.reference}/payment-qr`); const qrData = qrResponse.ok ? await qrResponse.json() : null; setQrCode(qrData?.qrCodeDataUrl ?? ''); } } catch (error) { setMessage(error instanceof Error ? error.message : 'ไม่สามารถสร้างนัดหมายได้'); } finally { setLoading(false); } };
  const uploadSlip = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !reference) return; setLoading(true); setMessage(''); try { const payload = new FormData(); payload.append('slip', file); const response = await fetch(`${apiBase}/appointments/${reference}/slip`, { method: 'POST', body: payload }); if (!response.ok) { const data = await response.json(); throw new Error(data.message); } setStep(8); } catch (error) { setMessage(error instanceof Error ? error.message : 'แนบสลิปไม่สำเร็จ'); } finally { setLoading(false); } };
  return <section className="booking-page"><div className="container booking-shell"><Link className="booking-back" to="/patient/menu"><ChevronLeft size={18} /> กลับเมนูบริการ</Link><p className="eyebrow">จองคิวออนไลน์</p><h1>นัดหมายรับบริการทันตกรรม</h1><ol className="booking-steps" aria-label="ขั้นตอนการจอง">{bookingStepLabels.map((label, index) => <li className={displayedStep >= index + 1 ? 'booking-steps__item--active' : ''} key={label}>{index + 1}. {label}</li>)}</ol>{message && <p className="booking-message" role="alert">{message}</p>}
    {step === 1 && <div className="booking-card"><h2>เลือกหมวดบริการ</h2><p>เริ่มจากเลือกหมวด เพื่อแสดงเฉพาะหัตถการและทันตแพทย์ที่เปิดให้บริการ</p><div className="booking-choices">{categories.map((item) => <button type="button" aria-label={item} className="booking-choice booking-choice--category" onClick={() => selectCategory(item)} key={item}><strong>{item}</strong><span>ตัวอย่างหัตถการ: {(commonProceduresByCategory[item] ?? services.filter((serviceItem) => serviceItem.category === item).slice(0, 3).map((serviceItem) => serviceItem.name)).join(', ')}</span></button>)}</div></div>}
    {step === 2 && <div className="booking-card"><button type="button" className="text-button" onClick={() => setStep(1)}>← เปลี่ยนหมวดบริการ</button><h2>เลือกหัตถการ</h2><p>หมวดที่เลือก: <b>{category}</b></p><div className="booking-choices">{procedures.map((item) => <button type="button" className="booking-choice" onClick={() => selectService(item)} key={item.id}><strong>{item.name}</strong><b>{formatStartingPrice(item.priceLabel)}</b></button>)}</div></div>}
    {step === 3 && <div className="booking-card">{bookingFlow === 'PROCEDURE_AND_DENTIST' && <button type="button" className="text-button" onClick={() => setStep(2)}>← เปลี่ยนหัตถการ</button>}<h2>เลือกทันตแพทย์</h2><p>{bookingFlow === 'DENTIST_ONLY' ? 'เลือกทันตแพทย์เพื่อดูช่วงเวลาว่าง' : <>หัตถการที่เลือก: <b>{service?.name}</b></>}</p><div className="booking-choices">{loading ? <p>กำลังโหลดรายชื่อ...</p> : dentists.map((item) => <button type="button" className="booking-choice" onClick={() => selectDentist(item)} key={item.id}><strong>{item.name}</strong><span>{item.specialty}</span></button>)}</div></div>}
    {step === 4 && <div className="booking-card">{bookingFlow !== 'TIME_ONLY' && <button type="button" className="text-button" onClick={() => setStep(3)}>← เปลี่ยนทันตแพทย์</button>}<h2>เลือกวันและเวลาที่ต้องการ</h2><p>{bookingFlow === 'TIME_ONLY' ? 'เลือกช่วงเวลาสำหรับคิวกลางของคลินิก' : bookingFlow === 'DENTIST_ONLY' ? <>แสดงเฉพาะสล็อตของ <b>{dentist?.name}</b></> : <>แสดงเฉพาะสล็อตของ <b>{dentist?.name}</b> ที่ให้บริการ <b>{service?.name}</b></>}</p><div className="booking-date"><label htmlFor="booking-date">วันนัดหมาย</label><input id="booking-date" type="date" min={today} value={selectedDate} onChange={(event) => { setSelectedDate(event.target.value); setSlot(null); void loadAvailability(undefined, event.target.value); }} /><button type="button" className="button button--outline" onClick={() => loadAvailability()}>ดูเวลา</button></div><div className="slot-list">{loading ? <p>กำลังโหลดเวลา...</p> : slots.length ? slots.map((item) => <button className={slot?.id === item.id ? 'slot-button slot-button--selected' : 'slot-button'} type="button" key={item.id} onClick={() => setSlot(item)}><Clock3 size={16} /> {timeLabel(item.startsAt)} น.</button>) : <p>ไม่พบเวลาว่างในวันนี้ กรุณาเลือกวันอื่น</p>}</div><button className="button booking-next" type="button" disabled={!slot} onClick={() => setStep(5)}>ต่อไป: กรอกเบอร์โทร</button></div>}
    {step === 5 && <form className="booking-card" onSubmit={createBooking}><button type="button" className="text-button" onClick={() => setStep(4)}>← เปลี่ยนเวลา</button><h2>ยืนยันข้อมูลการนัดหมาย</h2><dl className="booking-summary">{bookingFlow === 'PROCEDURE_AND_DENTIST' && <><div><dt>หมวดบริการ</dt><dd>{category}</dd></div><div><dt>หัตถการ</dt><dd>{service?.name}</dd></div></>} {bookingFlow !== 'TIME_ONLY' && <div><dt>ทันตแพทย์</dt><dd>{dentist?.name}</dd></div>}<div><dt>เวลา</dt><dd>{selectedDate} · {slot && timeLabel(slot.startsAt)} น.</dd></div></dl><label className="booking-phone" htmlFor="phone">เบอร์โทรศัพท์สำหรับติดต่อ<input id="phone" type="tel" inputMode="numeric" pattern="0[0-9]{8,9}" required placeholder="0xx-xxx-xxxx" value={phone} onChange={(event) => setPhone(event.target.value)} /></label><p>ระบบใช้ SSO ในการลงชื่อเข้าใช้แล้ว จึงขอเพียงเบอร์โทรศัพท์เพื่อการติดต่อ</p><button className="button booking-next" disabled={loading} type="submit">{loading ? 'กำลังจอง...' : 'ยืนยันและรับหมายเลขคิว'}</button></form>}
    {step === 6 && <div className="booking-card booking-acknowledgement"><h2>โปรดรับทราบก่อนยืนยันการจองคิว</h2><p>กรุณามารับบริการตามวันและเวลาที่จองคิวไว้</p>{!reservationPaymentRequired && <p className="booking-acknowledgement__warning">หากไม่มาตามวันและเวลาที่จอง ท่านจะไม่สามารถจองผ่านระบบออนไลน์และทางโทรศัพท์ได้ ต้องวอล์กอินจองที่คลินิกเท่านั้น</p>}<label className="booking-acknowledgement__check"><input checked={acknowledged} type="checkbox" onChange={(event) => setAcknowledged(event.target.checked)} /> ข้าพเจ้ารับทราบและยืนยันการจองคิว</label><button className="button booking-next" disabled={!acknowledged} type="button" onClick={() => setStep(7)}>ยืนยันการรับทราบ</button></div>}
    {step === 7 && <div className="booking-card booking-payment"><CheckCircle2 size={42} /><h2>{reservationPaymentRequired ? 'จองคิวสำเร็จ รอยืนยันการชำระเงิน' : 'จองคิวสำเร็จ'}</h2><p>หมายเลขคิวของคุณ <b>{queueNumber}</b></p>{reservationPaymentRequired ? <><p>ยอดชำระ <b>{amount.toLocaleString()} บาท</b></p>{qrCode ? <><img src={qrCode} alt="QR code สำหรับชำระเงิน" /><a className="button button--outline" href={qrCode} download={`payment-${reference}.png`}>ดาวน์โหลด QR code</a></> : <p>กำลังสร้าง QR code...</p>}<label className="button booking-upload"><Upload size={17} /> แนบสลิปโอนเงิน<input type="file" accept="image/png,image/jpeg,application/pdf" onChange={uploadSlip} /></label><small>หลังแนบสลิป เจ้าหน้าที่จะตรวจสอบและยืนยันนัดหมายให้</small></> : <><p>นัดหมายของคุณอยู่ระหว่างรอเจ้าหน้าที่ยืนยันนัดหมาย</p><p>เมื่อเจ้าหน้าที่ดำเนินการแล้ว ระบบจะส่งข้อความยืนยันนัดหมายผ่านไลน์หมอพร้อม หรือแอปพลิเคชันหมอพร้อม</p><Link className="button" to="/patient/appointments">ดูคิวจอง</Link></>}</div>}
    {step === 8 && <div className="booking-card booking-payment"><CheckCircle2 size={48} /><h2>ส่งหลักฐานการโอนเงินเรียบร้อย</h2><p>หมายเลขคิว <b>{queueNumber}</b> อยู่ในสถานะ <b>รอเจ้าหน้าที่ตรวจสอบหลักฐานการโอนเงินจอง</b></p><p>เมื่อเจ้าหน้าที่ตรวจสอบและยืนยันนัดหมายแล้ว ระบบจะแจ้งผลผ่านแอปพลิเคชันหมอพร้อมของท่าน หรือท่านสามารถตรวจสอบสถานะคิวได้ที่เมนู <b>ดูคิวจอง</b></p><Link className="button" to="/patient/appointments">ดูคิวจอง</Link></div>}
    </div></section>;
}
